repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [ python, pyi ]

      - id: ruff-format
        exclude: streamlit_app/app.py
        types_or: [ python, pyi ]