name: Run tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CALCULATION_API_URL: ${{ secrets.CALCULATION_API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        env:
          PYTHONPATH: "./components:./documents:./calculation:./templates:./static:."
        run: uv run pytest -vv
